-- SpringBootStarterJDBC автоматически ищет и выполняет schema.sql и data.sql
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHOR
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);
CREATE TABLE GENRE
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID INT REFERENCES AUTHOR (ID),
    GENRE_ID  INT REFERENCES GENRE (ID)
);
